Project1/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Addresses where mail is delivered.</description>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Address__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <formula>Street__c + &quot; &quot; + City__c + &quot;, &quot; + TEXT(State__c) + &quot; &quot; + Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mailing Address</label>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <description>Used to link contacts with addresses.</description>
    <label>Inhabitant</label>
    <nameField>
        <label>DestinationID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Packages for delivery.</description>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Package__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Addressee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Package__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Destination Contact and Address</description>
    <label>Destination</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Package__c/fields/Return__c.field-meta.xml
<CustomField>
    <fullName>Return__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Return Contact and Address.</description>
    <label>Return</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Packages (Return)</relationshipLabel>
    <relationshipName>Packages1</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Package__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>What is the current status of the package</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/classes/getPackage.cls
public class getPackage {
    
    public String TrackingID {get;set;}
    public Package__c pkg {get;set;}
    public Contact ct {get;set;}
    public Address__c addr {get;set;}
    
    public void find(){
    	
        List<Package__c> pkgs = new List<Package__c>();
        List<Inhabitant__c> inhs = new List<Inhabitant__c>();
        List<Contact> cts = new List<Contact>();
        List<Address__c> addrs = new List<Address__c>();
        
        try{
            pkgs = [SELECT Name, Status__c, Destination__c, Return__c FROM Package__c WHERE Name=:TrackingID WITH SECURITY_ENFORCED];
            pkg = pkgs[0];
            inhs = [SELECT Address__c, Contact__c FROM Inhabitant__c WHERE ID=:pkg.Destination__c];
            cts = [SELECT Name FROM Contact WHERE ID=:inhs[0].Contact__c];
            addrs = [SELECT Mailing_Address__c FROM Address__c WHERE ID=:inhs[0].Address__c];
            
            ct = cts[0];
            addr = addrs[0];
            
        }
        catch(exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'No package with that ID found.'));
        }
                
    }

}