Project1/force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Packages for delivery.</description>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Package__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>What is the current status of the package</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Package__c/recordTypes/Delivered.recordType-meta.xml
<RecordType>
    <fullName>Delivered</fullName>
    <active>true</active>
    <description>These packages have been delivered unless specified by customer support</description>
    <label>Delivered</label>
</RecordType>

Project1/force-app/main/default/objects/Package__c/recordTypes/Missing.recordType-meta.xml
<RecordType>
    <fullName>Missing</fullName>
    <active>true</active>
    <description>These packages have been declared missing by customer support</description>
    <label>Missing</label>
</RecordType>

Project1/force-app/main/default/classes/PackageDeliveryController.cls
public class PackageDeliveryController {
    public String filterChoice {get;set;}
    public List<SelectOption> possibleStates {get;set;}
    public packageDeliveryController(){
        filterChoice = 'Shipping';
        possibleStates = new List<SelectOption>();
        possibleStates.add(new SelectOption('Processing','Processing'));
        possibleStates.add(new SelectOption('Shipping','Shipping'));
        possibleStates.add(new SelectOption('Delivered','Delivered'));
        possibleStates.add(new SelectOption('Missing','Missing'));
    }
    public List<Package__c> getPackages(){
        List<Package__c> results = [SELECT Status__c, Name FROM Package__c WHERE Status__c=:filterChoice];
        //List<Package__c> results = Database.query('SELECT Status__c, Name FROM Package__c '+
        //                                          'WHERE Status__c = '+ filterChoice);
        return results;
    }
    
    public void showShipping(){
        this.filterChoice = 'Shipping';
    }
    public void showDelivered(){
        this.filterChoice = 'Delivered';
    }
    public void showMissing(){
        this.filterChoice = 'Missing';
    }
    public void showProcessing(){
        this.filterChoice = 'Processing';
    }
}